apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: code-with-quarkus-admin
subjects:
  - kind: ServiceAccount
    name: code-with-quarkus
    namespace: default
roleRef:
  kind: ClusterRole
  name: quarkus-operator-example
  apiGroup: ""