apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.example.com
spec:
  group: example.com
  names:
    kind: HelloWorld
    plural: helloworlds
    shortNames:
      - hw
    singular: helloworld
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                replicas:
                  type: integer
                image:
                  type: string
                data:
                  type: string
              type: object
            status:
              properties:
                readyReplicas:
                  type: integer
              type: object
          type: object
      served: true
      storage: true